-- VALURISE: invite links are generated by the Master and redeemed only by the
-- newly authenticated recipient. They never grant financial-data access.
create table if not exists public.access_invites (
  id uuid primary key default gen_random_uuid(),
  token uuid not null unique default gen_random_uuid(),
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null default (now() + interval '7 days'),
  used_by uuid references auth.users(id) on delete set null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  check ((used_by is null) = (used_at is null))
);

create index if not exists access_invites_created_by_idx
  on public.access_invites(created_by, created_at desc);

alter table public.access_invites enable row level security;

create policy "masters manage access invites" on public.access_invites for all to authenticated
  using ((select public.current_user_is_master()) and created_by = (select auth.uid()))
  with check ((select public.current_user_is_master()) and created_by = (select auth.uid()));

create or replace function public.redeem_access_invite(p_token uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  update public.access_invites
  set used_by = auth.uid(), used_at = now()
  where token = p_token
    and used_by is null
    and expires_at > now();
  if not found then raise exception 'invite unavailable'; end if;
end;
$$;

revoke all on function public.redeem_access_invite(uuid) from public;
grant execute on function public.redeem_access_invite(uuid) to authenticated;
